version: '3.1'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: weatherdb
    container_name: postgres16
    ports:
      - '5432:5432'
    volumes:
      - pgdb:/var/lib/postgresql/data
    expose:
      - '5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run start:prod'
    env_file:
      - .env
    container_name: nestjs
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  pgdb:
